[lxqt-base/lxqt-config] Depend on live version of libqtxdg.
lxqt-config-9999 fails to build against libqtxdg-1.1.0 with the following error:

iconthemeconfig.cpp:38:41: fatal error: private/qtxdg/qiconloader_p.h: No such file or directory